### ISSUE TITLE
On refresh getting error

### ISSUE THREAD

**Issue by nimitbhargava** [j-000/scratchpad#24]
On refreshing the page, I get the below error 👇 

![image](https://user-images.githubusercontent.com/8358694/64162115-60ed7a80-ce5c-11e9-9eab-b20e028c7607.png)

**Comment by nimitbhargava** [comment]
![image](https://user-images.githubusercontent.com/8358694/64162283-a742d980-ce5c-11e9-8248-81061ee1dc81.png)

I am able to access it ⬆️ 

But on refresh I get the same error.
I think it wasn't caused by me.

**Comment by j-000** [comment]
@nimitbhargava Hi! This is not an issue. S3 has a weird functionality that strips the /index.html from the URL when render the app.

What you see is the directory of the S3 bucket. If you want to render the page, append "/index.html" to the URL.

Refreshing ".../index.html" will redirect to the main directory of the S3 bucket (that image). 

The only way to avoid this would be to have a proper domain and configure it accordingly. 👍

**Comment by nimitbhargava** [comment]
Thanks for your explanation.

**Comment by j-000** [comment]
Closing this one. :+1:
