### ISSUE TITLE
Using Netlify for deployment instead of AWS Elastic BeanStalk?

### ISSUE THREAD

**Issue by nimitbhargava** [j-000/scratchpad#26]
Netlify deployment makes it very easy to deploy comparing with AWS Elastic BeanStalk.
It also includes CI/CD out of the box.
This is just a suggestion.

**Comment by j-000** [comment]
@nimitbhargava I confess I have never used Netlify. I am happy to give it a go after I learn some basics. 
How much of an effort would it involve?

**Comment by nimitbhargava** [comment]
I would say 5-10 mins of operation (connecting your repository to netlify and adding build command there)

I am available if you would like to pair up for this. 👍

**Comment by j-000** [comment]
@nimitbhargava sure thing! I will read up on Netlify. If you want you can start implementation and we can review it once you finish and you can let me know how it works? 😄

**Comment by nimitbhargava** [comment]
Sure, I will fork and create PR 👍 🔥

**Comment by j-000** [comment]
@nimitbhargava  Fantastic! 👍 While you are at it, update the readme.md and include your username in the "collaborators" section please 😄

**Comment by j-000** [comment]
@nimitbhargava  - using netlify! :+1: 
You were right, super simple to set up.

**Comment by nimitbhargava** [comment]
@j-000 Can you share `Build command` & `Publish directory` for the Netlify configuration?
