### ISSUE TITLE
Can't get regularTasks to work

### ISSUE THREAD

**Issue by j-000** [j-000/scratchpad#33]
I can't seem to get regularTasks to work. @crispinkoech  could you have a look? :thinking: 
It won't render anything and the dev console log "Cannot read property 'tasks' of undefined".

Note that I commented it out in the mean time so that the rest works. If you can get it to work, do another PR. 

I will keep trying to find the bug as well. 

Thanks! :sweat_smile:

**Comment by crispinkoech** [comment]
Just noticed this, I'll check it out 👍

**Comment by crispinkoech** [comment]
@j-000 I figure it out, it has to do with how we persist the app state to localStorage.

So, whenever the app is reloaded, we check the localStorage for a previously saved state and load it as our current state. This DOES NOT give a chance for any newly added state modules to be instantiated i.e the regularTasks state module never gets loaded.

Could you try clearing you localStorage and reloading the app? Tell me whether this fixes the issue.

As for a more permament solution, we should probably redo how the app state is persisted.

**Comment by j-000** [comment]
@crispinkoech Amazing work. :100: . Refreshing did solve the issue.
I think it is better to redo the bit of how app state is persusted.

What do you think would be a good approach to this?
Thank you for looking into this! :+1:

**Comment by crispinkoech** [comment]
For now, we could try loading a state module only if it is available in local storage. Something like so, in the "UPDATE_STATE" mutation: 
```
UPDATE_STATE(state, newstate){
      state.columns = newstate.columns
      state.timer = newstate.timer
     
      // Load this state only if a new version is available 
      // or if it is present in localStorage
      if (newstate.regularTasks) state.regularTasks = newstate.regularTasks  
},

```

I'd suggest we do this for all the other state modules as well as future state modules.

**Comment by crispinkoech** [comment]
This way, if it wasn't saved in localStorage, then vuex would initialize this module.

**Comment by j-000** [comment]
Seems reasonable, so why was I experiencing the issue? :thinking:

**Comment by crispinkoech** [comment]
Because, your version of scratchpad never had the regularTasks feature before, so your saved state never had the regularTasks state. This is where the "Cannot read property 'tasks' of undefined" error came from.

Refreshing allowed you to clear the saved state and save a new version that also includes the regularTasks state.

**Comment by j-000** [comment]
@crispinkoech got it! :+1: Okay, that's good. Really good detective work ahah.
So, if you're happy to include that if block, go ahead. Also include an if block for the timer module. 

I will raise a separate issue now with regards to some bugs I found about the regularTasks feature. :smile: But great job! I really like it.

**Comment by crispinkoech** [comment]
For sure  +1

**Comment by j-000** [comment]
Bugfix for loading state modules. #35
