### ISSUE TITLE
Minor bugs with Regular Tasks

### ISSUE THREAD

**Issue by j-000** [j-000/scratchpad#36]
@crispinkoech 
1)
```
// regularTasks.js
update_global_time({ commit }) {
    setInterval(() => {
      commit('UPDATE_GLOBAL_TIME')
    }, 1000)
  }

// RegularTasksPad.vue
created() {
    this.update_global_time();
  }
```

The `created()` methods is called everytime the tab "My Regular Tasks" is clicked. As a result the mapped action `update_global_time` is called and a new setInterval is generated. This creates multiple setIntervals when only one should be created. But there should not be a setInterval if no tasks exists. Finally, a settings optiong to customise the setInterval would be great (this helps with development as well).

2) When starting a regular task the clock starts on the `RegularTaskItem`. But if you click on any other tab and come back to the "My Regular Tasks" tab the clock is reset. This is probably due to the fact the created method is called again which updates the global time. 

To tackle these issue it would be best to come to an agreement for requirements.

User + App requirements

- [x] Users set regular tasks and can delete them
- [ ] Users can start and stop the timers in the regular tasks
- [ ] Users can navigate out of the "Regular Tasks" tab without affecting the state of the app
- [ ] When using `setInterval` the function needs to be global so that only one is created. Also there should be an option to manually change the interval time

Please feel free to add your suggestions. :smile:

**Comment by crispinkoech** [comment]
Agree on the first issue. The aim of the update_global_time() was to set a reactive property (accessible by all components) that returns the current time, since Date.now() isn't reactive. This makes sense so that it can be accessed by the regularTasks component, even the timer component. Perhaps we should add it on the top-level Vue instance "created" hook? And clear the interval on the beforeDestroy hook?

**Comment by j-000** [comment]
@crispinkoech Yes, I think that would be a good way to do this. Do you want to give it a go at this?

**Comment by crispinkoech** [comment]
Definitely.

**Comment by crispinkoech** [comment]
As for the second issue. Switching tabs tears down any component in the regularTasks pad, so any data/properties related to any entry task is lost. Still not sure how to solve this, but I'll research on it.

**Comment by j-000** [comment]
I understand. Perhaps if the setInterval changes to the created hook in the Vue instance, we would be able to solve this issue. I assume if the created hook of the vue instance is the only setInterval, then when the component is created it simply fetches (without changing) the data from the store (which is being evaluated/updated constantly). :thinking: would this not be the case?

**Comment by crispinkoech** [comment]
That would be the case, but each task's timer duration would be reset if the view is destroyed. Perhaps  we persist this to the state before destroy (in case a timer is still running) and reload it when the view is recreated? Then it would make sense to clear this from the state when the timer is stopped.

**Comment by j-000** [comment]
That's makes sense. A user starts a timer, if the view changes then save that running timer to global state, when the view is created check if a running timer was saved and fetch it but compute the correct remaining time (might need to also save the timestamp of the saved timer to compute the difference between the time it was saved beforeDestroyed and the time it was reinstated). 

Hope I make sense :smile:

**Comment by crispinkoech** [comment]
Actually, we can just save the timer's start time. This way, if a the view is recreated, we compute the difference using the current time and the start time (already doing this, so nothing changes).

**Comment by j-000** [comment]
Perfect! :+1:
